<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="css/style.css">
    <title>Agregar Nuevo Plan</title>
</head>
<body>
    <div class="item-plan contenedor-formulario">
        <h2 class="titulo-principal">Alta de Nuevo Plan</h2>

        <form action="add-plan" method="POST" class="formulario-alta">

            <div class="grupo-form">
                <label for="descripcion" class="descripcion">Descripción del plan:</label>
                <input type="text" id="descripcion" name="descripcion" required>
            </div>

            <div class="grupo-form">
                <label for="categoria" class="descripcion">Categoría (Ej: Viajes, Finanzas):</label>
                <input type="text" id="categoria" name="categoria" required>
            </div>

            <div class="grupo-form">
                <label for="monto_total" class="descripcion">Monto Total ($):</label>
                <input type="number" step="0.01" id="monto_total" name="monto_total" required>
            </div>

            <div class="grupo-form">
                <label for="id_cliente" class="descripcion">Asignar al Cliente:</label>
                <select id="id_cliente" name="id_cliente" required>
                    <option value="" disabled selected>Seleccione un cliente...</option>
                    
                    <?php foreach($clientes as $cliente): ?>
                        <option value="<?= $cliente->id_cliente ?>"><?= $cliente->nombre ?></option>
                    <?php endforeach; ?>
                    
                </select>
            </div>

            <button type="submit" class="enlace-detalle boton-guardar">
                Guardar Plan
            </button>
            <a href="planes" class="enlace-cancelar">Cancelar y volver al listado</a>
        </form>
    </div>
</body>
</html>